### ISSUE TITLE
Update package

### ISSUE THREAD

**Issue by pablo-gbr** [Astrotomic/php-deepface#11]
Hi, I've been looking at this package and its really helpful, but it wont install on symfony +7.0 and deepface made some changes to their package adding an anti_spoofing functionality that its currently missing on this package.

I updated the symfony version and added the new anti_spoofing thing. Do you want me to open a new pull request or are you going to update the package on your own?

Thanks!

**Comment by Gummibeer** [comment]
Hey, the Symfony update is done and released - so feel free to open a new MR for the new feature.
