### ISSUE TITLE
Unknown named parameter $left_eye

### ISSUE THREAD

**Issue by vkyeswa** [Astrotomic/php-deepface#8]
Thanks for this adapter, I have been trying to give it a go in my project however after setting up the Python environment that is required it gives me an error "Unknown named parameter $left_eye" when I try 

`$deepface->extractFaces(
  img_path: '~/test.png',
);`

Stack shows the error is  at ../vendor/astrotomic/php-deepface/src/DeepFace.php:184

**Comment by richardfrankza** [comment]
I also noticed this and I've sent a pull request
https://github.com/Astrotomic/php-deepface/pull/9

**Comment by Gummibeer** [comment]
MR is merged and released as v0.2.0
